# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_engine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'game_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11game_engine.proto\x12\x04game\":\n\x10StartGameRequest\x12\x13\n\x0bmax_players\x18\x01 \x01(\x05\x12\x11\n\tmax_turns\x18\x02 \x01(\x05\"8\n\x13PlayerActionRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"\x12\n\x10GameStateRequest\"\x12\n\x10ResetGameRequest\"\xcd\x01\n\tGameState\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_turn\x18\x02 \x01(\x05\x12\x11\n\tmax_turns\x18\x03 \x01(\x05\x12>\n\x10player_positions\x18\x04 \x03(\x0b\x32$.game.GameState.PlayerPositionsEntry\x12\x0f\n\x07players\x18\x05 \x03(\t\x1a\x36\n\x14PlayerPositionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xed\x01\n\nGameEngine\x12\x34\n\tStartGame\x12\x16.game.StartGameRequest\x1a\x0f.game.GameState\x12:\n\x0cPlayerAction\x12\x19.game.PlayerActionRequest\x1a\x0f.game.GameState\x12\x37\n\x0cGetGameState\x12\x16.game.GameStateRequest\x1a\x0f.game.GameState\x12\x34\n\tResetGame\x12\x16.game.ResetGameRequest\x1a\x0f.game.GameStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESTATE_PLAYERPOSITIONSENTRY']._loaded_options = None
  _globals['_GAMESTATE_PLAYERPOSITIONSENTRY']._serialized_options = b'8\001'
  _globals['_STARTGAMEREQUEST']._serialized_start=27
  _globals['_STARTGAMEREQUEST']._serialized_end=85
  _globals['_PLAYERACTIONREQUEST']._serialized_start=87
  _globals['_PLAYERACTIONREQUEST']._serialized_end=143
  _globals['_GAMESTATEREQUEST']._serialized_start=145
  _globals['_GAMESTATEREQUEST']._serialized_end=163
  _globals['_RESETGAMEREQUEST']._serialized_start=165
  _globals['_RESETGAMEREQUEST']._serialized_end=183
  _globals['_GAMESTATE']._serialized_start=186
  _globals['_GAMESTATE']._serialized_end=391
  _globals['_GAMESTATE_PLAYERPOSITIONSENTRY']._serialized_start=337
  _globals['_GAMESTATE_PLAYERPOSITIONSENTRY']._serialized_end=391
  _globals['_GAMEENGINE']._serialized_start=394
  _globals['_GAMEENGINE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
